#!/bin/bash

etcdirs="sysconfig default conf.d"

for x in $etcdirs; do
    d=/etc/$x/snapper
    if [[ -f $d ]]; then
	    sed -i 's@^SNAPPER_CONFIG.*@SNAPPER_CONFIG='$d'@g' bin/snap-sync
        exit 0
    fi
done

printf "==> Unable to find snapper configuration file in a standard location.\n"
printf "==> Using SNAPPER_CONFIG make variable.\n"
exit 1
